src/Entity/Starship.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Starship
 *
 * @ORM\Table(name="starship")
 * @ORM\Entity(repositoryClass="App\Repository\StarshipRepository")
 */
class Starship
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="name", type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(name="length", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $length;

    /**
     * @ORM\Column(name="hyperdrive_rating", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $hyperdrive_rating;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Person", mappedBy="starship")
     */
    private $person;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $edit_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ref;

    public function __construct()
    {
        $this->person = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLength(): ?string
    {
        return $this->length;
    }

    public function setLength(?string $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getHyperdriveRating(): ?string
    {
        return $this->hyperdrive_rating;
    }

    public function setHyperdriveRating(?string $hyperdrive_rating): self
    {
        $this->hyperdrive_rating = $hyperdrive_rating;

        return $this;
    }

    /**
     * @return Collection|Person[]
     */
    public function getPerson(): Collection
    {
        return $this->person;
    }

    public function addPerson(Person $person): self
    {
        if (!$this->person->contains($person)) {
            $this->person[] = $person;
            $person->addStarship($this);
        }

        return $this;
    }

    public function removePerson(Person $person): self
    {
        if ($this->person->contains($person)) {
            $this->person->removeElement($person);
            $person->removeStarship($this);
        }

        return $this;
    }


    public function getEditAt(): ?\DateTimeInterface
    {
        return $this->edit_at;
    }

    public function setEditAt(?\DateTimeInterface $edit_at): self
    {
        $this->edit_at = $edit_at;

        return $this;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }
}

src/Form/StarshipType.php
<?php

namespace App\Form;

use App\Entity\Starship;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StarshipType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('length')
            ->add('hyperdrive_rating')
            ->add('person')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Starship::class,
        ]);
    }
}

src/Controller/StarshipController.php
<?php

namespace App\Controller;

use App\Entity\Starship;
use App\Form\StarshipType;
use App\Repository\StarshipRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/starship")
 */
class StarshipController extends AbstractController
{
    /**
     * @Route("/", name="starship_index", methods={"GET"})
     */
    public function index(StarshipRepository $starshipRepository): Response
    {
        return $this->render('starship/index.html.twig', [
            'starships' => $starshipRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="starship_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $starship = new Starship();
        $form = $this->createForm(StarshipType::class, $starship);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($starship);
            $entityManager->flush();

            return $this->redirectToRoute('starship_index');
        }

        return $this->render('starship/new.html.twig', [
            'starship' => $starship,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="starship_show", methods={"GET"})
     */
    public function show(Starship $starship): Response
    {
        return $this->render('starship/show.html.twig', [
            'starship' => $starship,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="starship_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Starship $starship): Response
    {
        $form = $this->createForm(StarshipType::class, $starship);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('starship_index');
        }

        return $this->render('starship/edit.html.twig', [
            'starship' => $starship,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="starship_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Starship $starship): Response
    {
        if ($this->isCsrfTokenValid('delete'.$starship->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($starship);
            $entityManager->flush();
        }

        return $this->redirectToRoute('starship_index');
    }
}

templates/starship/_delete_form.html.twig
<form method="post" action="{{ path('starship_delete', {'id': starship.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE"><br>
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ starship.id) }}"><br>
    <button class="btn btn-danger">Delete</button>
</form>

templates/starship/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/starship/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Starship{% endblock %}

{% block body %}
    <h1>Edit Starship</h1>

    {{ include('starship/_form.html.twig', {'button_label': 'Update'}) }}

    <a class='btn btn-secondary' href="{{ path('starship_index') }}">back to list</a>

    {{ include('starship/_delete_form.html.twig') }}
{% endblock %}

templates/starship/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Starship index{% endblock %}

{% block body %}
<style>
  .back-button{position: fixed; top: 10px; left: 5px; padding: 10px 30px; border-radius: 5px; background: black; color: white; text-decoration: none;}
  .back-button:hover{font-weight: bold; transition: .5s ease; text-decoration: none; color: white;}
</style>

    <a class="back-button" href="{{ path('star_wars')}}">◄ Back</a>
    <h1>Starship index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Length</th>
                <th>Hyperdrive_rating</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for starship in starships %}
            <tr>
                <td>{{ starship.id }}</td>
                <td>{{ starship.name }}</td>
                <td>{{ starship.length }}</td>
                <td>{{ starship.hyperdriveRating }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('starship_show', {'id': starship.id}) }}">show</a>
                    <a class="btn btn-warning" href="{{ path('starship_edit', {'id': starship.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-info btn-lg btn-block" href="{{ path('starship_new') }}">Create new</a>
{% endblock %}

templates/starship/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Starship{% endblock %}

{% block body %}
    <h1>Create new Starship</h1>

    {{ include('starship/_form.html.twig') }}

    <a class='btn btn-secondary' href="{{ path('starship_index') }}">back to list</a>
{% endblock %}

templates/starship/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Starship{% endblock %}

{% block body %}
    <h1>Starship</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ starship.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ starship.name }}</td>
            </tr>
            <tr>
                <th>Length</th>
                <td>{{ starship.length }}</td>
            </tr>
            <tr>
                <th>Hyperdrive_rating</th>
                <td>{{ starship.hyperdriveRating }}</td>
            </tr>
        </tbody>
    </table>

    <a class='btn btn-secondary' href="{{ path('starship_index') }}">back to list</a>

    <a class='btn btn-warning' href="{{ path('starship_edit', {'id': starship.id}) }}">edit</a>

    {{ include('starship/_delete_form.html.twig') }}
{% endblock %}