src/Entity/Person.php
<?php

namespace App\Entity;

use App\Entity\Planete;
use App\Entity\Species;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="person")
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 */
class Person
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="name", type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(name="height", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $height;

    /**
     * @ORM\Column(name="masse", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $masse;

    /**
     * @ORM\Column(name="gender", type="string", length=30)
     */
    private $gender;

    /**
     * @var Planete
     *
     * @ORM\ManyToOne(targetEntity="Planete")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="planete_id", referencedColumnName="id")
     * })
     */
    private $planete;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Vehicule", inversedBy="person")
     * @ORM\JoinTable(name="person_vehicule",
     *   joinColumns={
     *     @ORM\JoinColumn(name="person_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="vehicule_id", referencedColumnName="id")
     *   }
     * )
     */
    private $vehicule;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Starship", inversedBy="person")
     * @ORM\JoinTable(name="person_starship",
     *   joinColumns={
     *     @ORM\JoinColumn(name="person_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="starship_id", referencedColumnName="id")
     *   }
     * )
     */
    private $starships;

    /**
     * @var Species
     *
     * @ORM\ManyToOne(targetEntity="Species")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="specy_id", referencedColumnName="id")
     * })
     */
    private $specy_id;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $edit_at;

    public function __construct()
    {
        $this->vehicule = new ArrayCollection();
        $this->starships = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHeight(): ?string
    {
        return $this->height;
    }

    public function setHeight(?string $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getMasse(): ?string
    {
        return $this->masse;
    }

    public function setMasse(?string $masse): self
    {
        $this->masse = $masse;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getPlanete()
    {
        return $this->planete;
    }

    public function setPlanete(?Planete $planete): self
    {
        $this->planete = $planete;

        return $this;
    }

    /**
     * @return Collection|Vehicule[]
     */
    public function getVehicule(): Collection
    {
        return $this->vehicule;
    }

    public function addVehicule(Vehicule $vehicule): self
    {
        if (!$this->vehicule->contains($vehicule)) {
            $this->vehicule[] = $vehicule;
        }

        return $this;
    }

    public function removeVehicule(Vehicule $vehicule): self
    {
        if ($this->vehicule->contains($vehicule)) {
            $this->vehicule->removeElement($vehicule);
        }

        return $this;
    }

    /**
     * @return Collection|Starship[]
     */
    public function getStarships(): Collection
    {
        return $this->starships;
    }

    public function addStarship(StarShip $starship): self
    {
        if (!$this->starships->contains($starship)) {
            $this->starships[] = $starship;
        }

        return $this;
    }

    public function removeStarship(StarShip $starship): self
    {
        if ($this->starships->contains($starship)) {
            $this->starships->removeElement($starship);
        }

        return $this;
    }

    public function getSpecyId()
    {
        return $this->specy_id;
    }

    public function setSpecyId(?species $specy_id): self
    {
        $this->specy_id = $specy_id;

        return $this;
    }


    public function getEditAt(): ?\DateTimeInterface
    {
        return $this->edit_at;
    }

    public function setEditAt(?\DateTimeInterface $edit_at): self
    {
        $this->edit_at = $edit_at;

        return $this;
    }

}

src/Form/PersonType.php
<?php

namespace App\Form;

use App\Entity\Person;
use App\Entity\Planete;
use App\Entity\Species;
use App\Entity\Starship;
use App\Entity\Vehicule;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('height')
            ->add('masse')
            ->add('gender')
            ->add('planete', EntityType::class, [
                'class' => Planete::class,
                'choice_label' => 'name'
                
            ])
            ->add('vehicule', EntityType::class, [
                'class' => Vehicule::class,
                'choice_label' => 'name'
            ])
            ->add('starships', EntityType::class, [
                'class' => Starship::class,
                'choice_label' => 'name'
            ])
            ->add('specy_id', EntityType::class, [
                'class' => Species::class,
                'choice_label' => 'name'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Person::class,
        ]);
    }
}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Form\PersonType;
use App\Repository\PersonRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/person")
 */
class PersonController extends AbstractController
{
    /**
     * @Route("/", name="person_index", methods={"GET"})
     */
    public function index(PersonRepository $personRepository): Response
    {
        return $this->render('person/index.html.twig', [
            'people' => $personRepository->findAll()
        ]);
    }

    /**
     * @Route("/new", name="person_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $person = new Person();
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($person);
            $entityManager->flush();

            return $this->redirectToRoute('person_index');
        }

        return $this->render('person/new.html.twig', [
            'person' => $person,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="person_show", methods={"GET"})
     */
    public function show(Person $person): Response
    {
        return $this->render('person/show.html.twig', [
            'person' => $person,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="person_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Person $person): Response
    {
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('person_index');
        }

        return $this->render('person/edit.html.twig', [
            'person' => $person,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="person_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Person $person): Response
    {
        if ($this->isCsrfTokenValid('delete'.$person->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($person);
            $entityManager->flush();
        }

        return $this->redirectToRoute('person_index');
    }
}

templates/person/_delete_form.html.twig
<form method="post" action="{{ path('person_delete', {'id': person.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE"><br>
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ person.id) }}"><br>
    <button class="btn btn-danger">Delete</button><br>
</form>

templates/person/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/person/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Person{% endblock %}

{% block body %}
    <h1>Edit Person</h1>

    {{ include('person/_form.html.twig', {'button_label': 'Update'}) }}

    <a class='btn btn-secondary' href="{{ path('person_index') }}">back to list</a>

    {{ include('person/_delete_form.html.twig') }}
{% endblock %}

templates/person/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Person index{% endblock %}

{% block body %}
<style>
  .back-button{position: fixed; top: 10px; left: 5px; padding: 10px 30px; border-radius: 5px; background: black; color: white; text-decoration: none;}
  .back-button:hover{font-weight: bold; transition: .5s ease; text-decoration: none; color: white;}
</style>

    <a class="back-button" href="{{ path('star_wars')}}">◄ Back</a>
    <h1>Person index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Height</th>
                <th>Masse</th>
                <th>Gender</th>
                <th>Planete</th>
                <th>vehicule</th>
                <th>starships</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for person in people %}
            <tr>
                <td>{{ person.id }}</td>
                <td>{{ person.name }}</td>
                <td>{{ person.height }}</td>
                <td>{{ person.masse }}</td>
                <td>{{ person.gender }}</td>
                {% if person.planete.name %}
                    <td>{{ person.planete.name}}</td>
                {% else %}
                    <td> Unknow </td>
                {% endif %}
                <td>
                {% for vehicule in person.vehicule %}
                   {{ vehicule.name}} <br>
                {% endfor %}
                </td>
                <td>
                {% for starships in person.starships %}
                    {{ starships.name}} <br>
                {% endfor %}
                </td>
                <td>
                    <a class="btn btn-primary" href="{{ path('person_show', {'id': person.id}) }}">show</a>
                    <a class="btn btn-warning" href="{{ path('person_edit', {'id': person.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-info btn-lg btn-block" href="{{ path('person_new') }}">Create new</a>
{% endblock %}

templates/person/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Person{% endblock %}

{% block body %}
    <h1>Create new Person</h1>

    {{ include('person/_form.html.twig') }}

    <a class='btn btn-secondary' href="{{ path('person_index') }}">back to list</a>
{% endblock %}

templates/person/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Person{% endblock %}

{% block body %}
    <h1>Person</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ person.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ person.name }}</td>
            </tr>
            <tr>
                <th>Height</th>
                <td>{{ person.height }}</td>
            </tr>
            <tr>
                <th>Masse</th>
                <td>{{ person.masse }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ person.gender }}</td>
            </tr>
            <tr>
                <th>Edit_at</th>
                <td>{{ person.editAt ? person.editAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class='btn btn-secondary' href="{{ path('person_index') }}">back to list</a>

    <a class='btn btn-warning' href="{{ path('person_edit', {'id': person.id}) }}">edit</a>

    {{ include('person/_delete_form.html.twig') }}
{% endblock %}